# Generated by Django 5.1 on 2024-08-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='actors/')),
                ('bio', models.TextField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('bio', models.TextField(max_length=600, null=True)),
                ('image', models.ImageField(null=True, upload_to='directors/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=900, null=True)),
                ('release_date', models.DateField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('poster_image', models.ImageField(null=True, upload_to='posters/')),
                ('actors', models.ManyToManyField(null=True, to='movies.actor')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
        ),
    ]
